language: scala
jdk: oraclejdk8
script: project/travis.sh

addons:
  apt:
    packages:
    - graphviz

env:
  global:
    - COURSIER_PROGRESS=0
  matrix:
    - TRAVIS_SBT_VERSION=1.x
    - TRAVIS_SBT_VERSION=0.13.x

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
